source 'https://gem.coop'

gem 'importmap-rails', '~> 2.2'
gem 'pagy', '~> 43.6'
gem 'propshaft', '~> 1.3'
gem 'puma', '~> 8.0'
gem 'rails', '~> 8.1'
gem 'ros-apartment', '~> 3.4', require: 'apartment'
gem 'rotp', '~> 6.3'
gem 'sqlite3', '~> 2.9'
gem 'stimulus-rails', '~> 1.3'
gem 'turbo-rails', '~> 2.0'

group :development, :test do
  gem 'debug'
end
